#!/bin/sh

x() {
    n=$(basename "$1")
    [ -f "$n" ] && echo "$n already fetched" || wget "$1"
}
x http://ftp.gnu.org/gnu/binutils/binutils-2.25.1.tar.gz
x http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz
x ftp://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/powerpc/ISO-IMAGES/6.3/6.3-RELEASE-powerpc-disc1.iso
x http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.3.tar.xz
x http://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
x http://ftp.gnu.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.bz2

S=`sha1sum 6.3-RELEASE-powerpc-disc1.iso | awk '{print $1}'`
if [ "$S" != "5bb7a80f8aa2568a57826aa6bd35d2e171566fec" ]
then
    >&2 echo "Error: sha1sum does not match"
    exit 1
fi

rm -rf freebsd
mkdir -p freebsd
(cd freebsd &&
 7z x ../6.3-RELEASE-powerpc-disc1.iso 6.3-RELEASE/base/base.?? &&
 cat 6.3-RELEASE/base/base.?? | tar xzf - ./usr/include ./usr/lib ./lib ./usr/share/mk &&
 rm -fr 6.3-RELEASE
 ) || return 1

docker build -t 'freebsd-powerpc-cross-build:6.3' .
ret=$?
rm -fr freebsd/

exit $ret

