#!/bin/sh

x() {
    n=$(basename "$1")
    [ -f "$n" ] && echo "$n already fetched" || wget -O "$n" "$1"
}

x http://ftp.gnu.org/gnu/binutils/binutils-2.32.tar.gz
x http://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.xz
x http://download.freebsd.org/ftp/releases/arm64/12.0-RELEASE/base.txz
#x http://download.freebsd.org/ftp/releases/arm64/12.0-RELEASE/src.txz

S=`sha1sum base.txz | awk '{print $1}'`
if [ "$S" != "007130d6e805c2bf2888485eb0c3c3b34e0137ec" ]
then
    >&2 echo "Error: sha1sum of base.txz does not match"
    exit 1
fi

rm -rf freebsd
mkdir -p freebsd
(cd freebsd &&
 tar xJf ../base.txz ./usr/include ./usr/lib ./lib ./usr/share/mk
 ) || return 1

docker build -t 'freebsd-aarch64-cross-build:12.0' "$@" .
ret=$?
rm -fr freebsd/

exit $ret

