#!/bin/sh

# fix all links that point to absolute paths to point according to /freebsd
prefix="$1"
triplet="$2"

dirs=''
test -d "$prefix/lib"      && dirs="$dirs $prefix/lib"
test -d "$prefix/usr"      && dirs="$dirs $prefix/usr"
test -d "$prefix/$triplet" && dirs="$dirs $prefix/$triplet"
test -z "$dirs" && dirs=.

links=`find $dirs -type l`

for l in $links; do
  ldest=`readlink "$l"`
  bl=`basename "$l"`
  case "$ldest" in
    '')
      ;;
    /lib/*.so*|../../lib/*.so*)
      bdest=`basename "$ldest"`
      destdir="$DESTDIR$prefix/$triplet/lib"
      echo "** Fixing shared lib link: $bdest -> $destdir/$bl" 1>&2
      mkdir -p "$destdir"
      rm -f "$l"
      ln -sf "$bdest" "$destdir/$bl"
      ;;
      
    /usr/include/*.h)
      bdest=`basename "$ldest"`
      dest="$DESTDIR$prefix/$triplet/include/$bdest"
      echo "** Fixing header link: $bdest -> $destdir/$bl" 1>&2
      mkdir -p "$destdir"
      rm -f "$l"
      ln -sf "$bdest" "$destdir/$bl"
      ;;
    *)
      #echo "** Leaving link: $l -> $ldest" 1>&2
      ;;
  esac
done

ldscripts=`fgrep -rIl 'GROUP ('  "$prefix" 2> /dev/null | grep '\.so$'`
for s in $ldscripts; do
  sed -i '/GROUP (/s:\([ ]*\)\(/usr\)*/lib/:\1:g' "$s"
done


#ln -sf $prefix/lib/gcc/$triplet/4.8.5/libgcc.a   $DESTDIR$prefix/$triplet/lib/libgcc.a
#ln -sf $prefix/lib/gcc/$triplet/4.8.5/libgcc_p.a $DESTDIR$prefix/$triplet/lib/libgcc_p.a

